---
# tasks file for configure_eks
- name: Configure kubeconfig
  shell: >
    aws eks update-kubeconfig
    --region {{ aws_region }}
    --name {{ cluster_name }}

- name: Verify cluster connectivity
  command: kubectl get nodes
  register: nodes

- debug:
    var: nodes.stdout_lines
