apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: abc-tech
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jsachdev07/tf-eks-ci-cd.git
    targetRevision: master
    path: k8s-argo
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
