---
# tasks file for argocd
- name: Install ArgoCD
  kubernetes.core.k8s:

    state: present

    src: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

- name: Wait for ArgoCD Server
  shell: >
    kubectl rollout status
    deployment/argocd-server
    -n argocd
    --timeout=600s
